In [1]:
import numpy as np
import pandas as pd
data={"area": [2600 ,3000,3200,3600,4000,4100],
      "bedrooms":[3,4,np.NaN,3,5,6],
      "age":[20,15,18,30,8,8],
      "price":[550000,565000,610000,595000,760000,810000]}
df=pd.DataFrame(data)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [2]:
df=df.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(df[["area","bedrooms","age"]],df["price"])

LinearRegression()

In [4]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [5]:
model.intercept_

221323.0018654043

In [6]:
model.predict([[3000,3,40]])


array([498408.25158031])

In [7]:
112.06*3000+3*23388.8-3231.717*40+221323.0018654043

498400.72186540434

In [8]:
model.predict([[2500,4,5]])

array([578876.03748933])

# hiring.csv

In [9]:
df1=pd.read_csv("hiring.csv")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df1["test_score(out of 10)"]=df1["test_score(out of 10)"].fillna(df1["test_score(out of 10)"].mean())
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN               8.000000                           9      50000
1        NaN               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [11]:
df1["experience"]=df1["experience"].fillna("zero")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero               8.000000                           9      50000
1       zero               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [12]:
from word2number import w2n
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [13]:
df1['test_score(out of 10)']=df1['test_score(out of 10)'].astype(int)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                      7                           7      72000
7          11                      7                           8      80000

In [14]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(df1[["experience","test_score(out of 10)","interview_score(out of 10)"]],df1["salary($)"])


LinearRegression()

In [15]:
model.predict([[2,9,6]])

array([53713.86677124])

In [16]:
model.predict([[12,10,10]])

array([93747.79628651])