In [1]:
dict1={"Name": ["mridul","ricky","sonal","mohit",],
       "age":[26,20,None,25],
       "height":[5.8,5.9,5.5,None],
       "places":[None,"ropar","kota","kota"]
      }

In [2]:
import pandas as pd
df=pd.DataFrame(dict1)
df.isnull().sum()#calculates no. of missing values

Name      0
age       1
height    1
places    1
dtype: int64

In [3]:

df["age"]=df["age"].fillna(df["age"].mean())
#we could use .dropna to delete entire row
df

Name        age  height places
0  mridul  26.000000     5.8   None
1   ricky  20.000000     5.9  ropar
2   sonal  23.666667     5.5   kota
3   mohit  25.000000     NaN   kota

In [4]:

df["height"]=df["height"].fillna(df["height"].mean())
print(df)

     Name        age    height places
0  mridul  26.000000  5.800000   None
1   ricky  20.000000  5.900000  ropar
2   sonal  23.666667  5.500000   kota
3   mohit  25.000000  5.733333   kota


In [5]:
df["places"]=df["places"].fillna(df["places"].value_counts().index[0])
df#index=0 value counts most values in column

Name        age    height places
0  mridul  26.000000  5.800000   kota
1   ricky  20.000000  5.900000  ropar
2   sonal  23.666667  5.500000   kota
3   mohit  25.000000  5.733333   kota

In [6]:
import numpy as np
from sklearn.impute import SimpleImputer
test = pd.Series(range(6))
test.loc[2:4]=np.nan
test

0    0.0
1    1.0
2    NaN
3    NaN
4    NaN
5    5.0
dtype: float64

In [7]:
test.fillna(method='ffill')#orbfill


0    0.0
1    1.0
2    1.0
3    1.0
4    1.0
5    5.0
dtype: float64

In [8]:
test.interpolate()

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float64

In [9]:
X = pd.DataFrame({'Shape':['square', 'square', 'oval', 'circle', np.nan]})
X

Shape
0  square
1  square
2    oval
3  circle
4     NaN

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
x=imputer.fit_transform(X)
x

array([['square'],
       ['square'],
       ['oval'],
       ['circle'],
       ['square']], dtype=object)

In [11]:
df=pd.DataFrame(x)
df

0
0  square
1  square
2    oval
3  circle
4  square

In [12]:
imputer=SimpleImputer(strategy="constant",fill_value='missing')
imputer.fit_transform(X)

array([['square'],
       ['square'],
       ['oval'],
       ['circle'],
       ['missing']], dtype=object)

In [13]:
import pandas as pd
df = pd.read_csv('http://bit.ly/kaggletrain', nrows=6)
cols = ['SibSp', 'Fare', 'Age']
print(cols)
X = df[cols]
X


['SibSp', 'Fare', 'Age']


SibSp     Fare   Age
0      1   7.2500  22.0
1      1  71.2833  38.0
2      0   7.9250  26.0
3      1  53.1000  35.0
4      0   8.0500  35.0
5      0   8.4583   NaN

In [14]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
impute_it = IterativeImputer()
impute_it.fit_transform(X)
#uses age as label adn others as features to predict missing age

array([[ 1.        ,  7.25      , 22.        ],
       [ 1.        , 71.2833    , 38.        ],
       [ 0.        ,  7.925     , 26.        ],
       [ 1.        , 53.1       , 35.        ],
       [ 0.        ,  8.05      , 35.        ],
       [ 0.        ,  8.4583    , 28.50639495]])

In [15]:
from sklearn.impute import KNNImputer
impute_knn = KNNImputer(n_neighbors=2)
impute_knn.fit_transform(X)
#here neighbour size 2
#so uses 2 nearest values of other features to calculate mean for the age
#here 3rd and 5th row used

array([[ 1.    ,  7.25  , 22.    ],
       [ 1.    , 71.2833, 38.    ],
       [ 0.    ,  7.925 , 26.    ],
       [ 1.    , 53.1   , 35.    ],
       [ 0.    ,  8.05  , 35.    ],
       [ 0.    ,  8.4583, 30.5   ]])

In [16]:
import pandas as pd
import numpy as np
X = pd.DataFrame({'Age':[20, 30, 10, np.nan, 10]})
X


Age
0  20.0
1  30.0
2  10.0
3   NaN
4  10.0

In [17]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer()
imputer.fit_transform(X)

array([[20. ],
       [30. ],
       [10. ],
       [17.5],
       [10. ]])

In [18]:
imputer=SimpleImputer(add_indicator=True)
imputer.fit_transform(X)# new features representing missing values

array([[20. ,  0. ],
       [30. ,  0. ],
       [10. ,  0. ],
       [17.5,  1. ],
       [10. ,  0. ]])